# NOÇÕES GERAIS DE PYTHON

## 1. Variáveis e objetos

### Variável:
- "Espaço em memória, para guardar um valor durante a execução de um programa.
- Por exemplo, você tem um programa para prever as vendas. Você vai precisar de uma variável para, por exemplo, saber quantos meses para frente o programa deve prever.
- Tem um tipo:
  * Texto (string). Ex.: nome.
  * Inteiro. Ex.: idade.
  * Float. Ex.: altura.
  * Lógico (falso e verdadeiro).
- A declaração de variáveis no Python é ímplicita.
- No Python:
  * Cria variável do tipo inteiro (x = 1).
  * Cria variável do tipo float (y = 3.13).
  * Cria variável do tipo string (z = 'Python' ou z = "Pyhton)
  * Cria variável do tipo lógico (w = True e y = False)
- Exibir valores no console:
  * print(x)
  * print("Este texto erá impresso no console")
  * print("Texto e duas variáveis", x, z)
- Verificar tipo:
  * type(x)
- Entrada de valores:
  * x = input("Informe um valor")
  * OBS.:
    - Aguarda o uduário digitar o dado.
    - Cria a variável x como string e armazena o valor.
    - Independente do tipo de dado informado, a variável será sempre string.
- Conversão de valores:
  * x = int(z)
  * w = str(m)
  * t = float(l)

In [ ]:
# Cria variável do tipo inteiro
x = 1
print(x)

In [ ]:
# Cria variável do tipo float
y = 3.13
print(x)

In [ ]:
# Cria variável do tipo string
m = "Python"
m

In [ ]:
m = 'Python'
m

In [ ]:
# Cria variável do tipo lógica
w = True
y = True
print(y)

In [ ]:
# Calculadora
x = 10
y = 20
z = 100
w = (x + y) * z / 100
w

In [ ]:
# Exibir texto no console
print("Este texto será impresso no console")

In [ ]:
print(x)

In [ ]:
print("Texto e duas variáveis: ", x, ", ", z)

In [ ]:
# Verificar tipo
print(type(x))

In [ ]:
print(type(m))

In [ ]:
# Entrada de dados
print("Informe o valor: ")
i = input()
# Mostra tipo de string
print(type(i))

In [ ]:
# Conversão de valores para inteiro
var = input("Informe o valor: ")
print(type(var))

In [ ]:
var = int(var)
print(type(var))

In [ ]:
# Conversão para float
var = input("Informe o valor: ")
print(type(var))

In [ ]:
var = float(var)
print(type(var))

## 2. Estruturas de decisão

- O programa deve decidir entre diferentes fluxos, de acordo com entradas.

- Por exemplo, se a nota de um aluno é maior ou igual a 7, ele é aprovado, caso contrário é reprovado.

In [1]:
nota = 7
if nota >= 7:
    print('Aprovado')
    print('Parabéns!')
else:
    print("Reprovado")

Aprovado
Parabéns!


In [2]:
# Só mudar o valor da variável
nota = 5
if nota >= 7:
    print('Aprovado')
else:
    print('Reprovado')

Reprovado


In [3]:
# Testar com 4, 5 e 7
nota = 7
if nota <= 4:
    print('Reprovado')
elif nota > 4 and nota <= 6:
    print('Exame')
else:
    print('Aprovado')

Aprovado


## 3. Estruturas de repetição

- Muitas vezes estruturas de Código tem que ser repetidas
- Em muitos casos, estas repetições são definidads dinamicamente (input do usuário)
- Dois tipos principais:
  * Executa enquanto condição lógica for verdadeira
  * Executa um número n de vezes

In [4]:
# Exemplo com while
count = 1
while count <= 5:
    print(count)
    count += 1

1
2
3
4
5


In [5]:
# range (0, 10, 1)
# range (ínicio, parada, incremento)
# O python "ignora" o último valor de intervalos 
# O incremento pode ser negativo

# for normal
for n in range(0,10):
    print(n+1)

for n in range(1, 11):
    print(n)

1
2
3
4
5
6
7
8
9
10
1
2
3
4
5
6
7
8
9
10


In [6]:
# for decrescente
for n in range (10, 0, -1):
    print(n)

10
9
8
7
6
5
4
3
2
1


In [7]:
# Exemplo com break
# vai parar no 3 pois o break está antes do print
for n in range(0, 10):
    if n==4:
        break
    print(n)

0
1
2
3


In [8]:
# Exemplo com continue 
# Vai pular o número 4
for n in range(0, 10):
    if n==4:
        continue
    print(n)

0
1
2
3
5
6
7
8
9


## 4. Listas

- Vetor de Valores
- Dados não precisam ser do mesmo tipo
- Criando Listas:
  * lst = [1,2,3,4,5]
  * lst2 = [1,2,3,"4",True]
  * lst3 = [12,[1,2,3,4,5],"a"]
  * lst4 = list(range(0,10))
- Acesso ao primeiro elemento – indexadas em zero:
  * lst [0]
- Número de elementos em uma lista:
  * len (lst)

In [ ]:
# Forma de criar listas
lst = [1,2,3,4,5]
print(lst)

In [ ]:
# Listas de vários tipos
lst2 = [1,2,3,"4",True]
print(lst)

In [ ]:
# Lista com lista
lst3 = [12,[1,2,3,4,5],"a"]
lst3

In [ ]:
# Criando lista com range
lst4 = list(range(0,10))
lst4

In [ ]:
# Comprimento da lista
print(len(lst))

In [ ]:
# Acessando elemento
print(lst[0])

In [ ]:
# Posição 1 de uma lista
print(lst3[1])

In [ ]:
# Alterando a prosição
lst[0]=4
print(list)

In [ ]:
# Percorrendo lista
for n in range(0, len(lst4)):
    print(lst4[n]+1)

## 5. Dicionários, sets e tuplas

#### Dicionários:
- Conjunto de chave/valor associados
- Declarados por chaves e separados por dois pontos
- Ex.: Precos = {'lapis':5.5, 'borracha':7.0, 'caneta': 6.5}

#### Sets:
- Conjuntos não ordenados e não repetidos de elementos.
- animais = {'gato', 'cachorro'}

#### Tuplas
- São listas que não podem ser alteradas
- Ex.: tp1 = (1,2,3,4,5,6)

In [9]:
# Dicionários: estrutura chave/valor
Notas = {'João': 6.0, 'Maria': 8.0, 'Pedro': 6.5}
print(Notas)

{'João': 6.0, 'Maria': 8.0, 'Pedro': 6.5}


In [10]:
print(Notas['João'])

6.0


In [11]:
# Todas as chaves
Notas.keys()

dict_keys(['João', 'Maria', 'Pedro'])

In [12]:
# Todos os valores
Notas.values()

dict_values([6.0, 8.0, 6.5])

In [13]:
# Testa logicamente a existência
print('João' in Notas)
print('Fernanda' in Notas)

True
False


In [14]:
# Apaga um elemento
del Notas['João']
print(Notas)

{'Maria': 8.0, 'Pedro': 6.5}


In [15]:
# Inclui um elemento
Notas['Ana'] = 9
print(Notas)

{'Maria': 8.0, 'Pedro': 6.5, 'Ana': 9}


In [16]:
# Busca um valor, se não encontrar mostra segundo parâmetro
Notas.get('Geraldo', 'Não encontrado!')

'Não encontrado!'

In [17]:
# Sets são conjuntos não ordenados de elementos repetidos
bigdata = {'Spark', 'Hive', 'Sqoop'}
print(bigdata)

{'Hive', 'Spark', 'Sqoop'}


In [18]:
# Verifica existência
print('Spark' in bigdata)

True


In [19]:
# Adiciona elemento
bigdata.add('Hadoop')
bigdata

{'Hadoop', 'Hive', 'Spark', 'Sqoop'}

In [20]:
# Número de elementos
print(len(bigdata))

4


In [22]:
bigdata.add("Spark")
bigdata

{'Hadoop', 'Hive', 'Spark', 'Sqoop'}

In [23]:
# Tuplas são listas que não são alteradas
# listas usam [], tuplas()
tupla = (1,2,3,4,5,6,7)
tupla

(1, 2, 3, 4, 5, 6, 7)

In [24]:
tupla[4]

5

In [26]:
# Dicionários em que cada posição recebe a tupla
dic2 = {(0,1):1, (1,2):1, (2,3):2, (3,4):3, (4,5):4, (6,7):5, (7,8):6, (8,9):7, (9,10):9}
dic2

{(0, 1): 1,
 (1, 2): 1,
 (2, 3): 2,
 (3, 4): 3,
 (4, 5): 4,
 (6, 7): 5,
 (7, 8): 6,
 (8, 9): 7,
 (9, 10): 9}

In [27]:
print(type(Notas))

<class 'dict'>


In [28]:
print(type(bigdata))

<class 'set'>


In [29]:
print(type(tupla))

<class 'tuple'>


## 6. Numpy

- Computação cientifica: facilitam operações matemáticas avançadas e outros tipos de operações em muitos dados.
- Objeto da matriz multidimensional.
- Variedade de rotinas para operações rápidas em matrizes.
- Os arrays Numpy têm um tamanho fixo na criação, ao contrário das listas Python (que podem crescer dinamicamente).
- Os elementos de uma matriz Numpy devem ser todos do mesmo tipo de dados e, portanto, terão o mesmo tamanho na memória.
- Ex.:
  * Importando o Numpy:
    - import numpy as np
  * Criando uma matriz unidimensional:
    - a = np.array ([12, 34, 26, 18, 10])
    - print(a)
    - print(a.dtype)

In [2]:
import numpy as np

In [92]:
# Cria uma matriz unidimensional
mt = np.array([12,34,26,18,10])
print(mt)

[12 34 26 18 10]


In [93]:
print(type(mt))

<class 'numpy.ndarray'>


In [94]:
# Criar o array com um tipo específico
# Criar o array como float de 64 bits
mtfloat = np.array([1,2,3], dtype = np.float64)
print(mt)

[12 34 26 18 10]


In [95]:
print(type(mt))

<class 'numpy.ndarray'>


In [97]:
# Mudar o tipo de array
# Podemos transformar tipos de dados de arrays
mtnew = np.array([1.4, 3.6, -5.1, 9.42, 4.99])
print(mtnew)

[ 1.4   3.6  -5.1   9.42  4.99]


In [98]:
# Quando transformamos de float para int os valores são truncados
mtnewint = mtnew.astype(np.int32)
print(mtnewint)

[ 1  3 -5  9  4]


In [100]:
# Podemos fazer o inverso também
mt5 = np.array([1,2,3,4])
print(mt5)

[1 2 3 4]


In [102]:
mt6 = mt5.astype(float)
print(mt6)

[1. 2. 3. 4.]


In [32]:
# Mais de uma dimensão
# Cria uma matriz bidimensional
mt7 = np.array([[7,2,23],[12,27,4],[5,4,23]])
print(mt7)

[[ 7  2 23]
 [12 27  4]
 [ 5  4 23]]


In [33]:
# Cria arrays vazios tipificados
# Empty significa que não são inicializados, não que são vazios
vazio = np.empty([3,2], dtype = int)
print(vazio)

[[241926064       412]
 [        0         0]
 [        1         0]]


In [34]:
print("------")

------


In [35]:
# Cria uma matriz 4x3 com valores 0
zeros  = np.zeros([4,3])
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [36]:
# Cria uma matriz com valores igual a 1
um = np.ones([5,7])
print(um)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [37]:
# Cria matriz quadrada com diagonal principal com valores 1 e os outros valores zero
diagonal = np.eye(5)
print(diagonal)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [38]:
# Valores aleatórios entre 0 e 1
ale = np.random.random((5))
print('ale')

ale


In [39]:
# Valores aleatórios com distribuição normal contendo negativos
ale2 = np.random.randn((5))
print(ale2)

[-1.45232049 -0.60249906  0.00299474 -0.3237994   0.09340957]


In [40]:
# Valores aleatórios 3x4
ale3 = (10*np.random.random((3,4)))
print(ale3)

[[7.16719808 9.01342468 5.19418311 7.97139148]
 [2.93322781 3.10298618 5.68606545 8.35567594]
 [6.9270045  5.34172108 2.71303938 9.88365763]]


In [41]:
# Outra forma de gerar aleatórios
# Uso da semente
grn = np.random.default_rng(1)
ale5 = grn.random(3)
print(ale5)

[0.51182162 0.9504637  0.14415961]


In [43]:
# Gerar inteiros
ale6 = grn.integers(10, size=(3,4))
print(ale6)

[[8 9 2 3]
 [8 4 2 8]
 [2 4 6 5]]


In [44]:
# Unique remove repetições
j = np.array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])
j = np.unique(j)
print(j)

[11 12 13 14 15 16 17 18 19 20]


In [45]:
# Funções específicas
# Cria a matriz bidimensional k
k = np.array([[17,22,43],[27,25,14],[15,24,32]])
# Mostra a matriz k
print(k)

[[17 22 43]
 [27 25 14]
 [15 24 32]]


In [46]:
# Mostra um elemento específico da matriz k
print(k[0][1])

22


In [47]:
# Mostra o tamanho das dimensões da matriz k
print(k.shape)

(3, 3)


In [48]:
# Funções Matemáticas
# Mostra o maior valor da matriz k
print(k.max())

43


In [49]:
# Mostra o menor valor da matriz k
print(k.min())

14


In [50]:
# Mostra a soma dos valores da matriz k
print(k.sum())

219


In [51]:
# Mostra o valor da média dos valores da matriz k
print(k.mean())

24.333333333333332


In [52]:
# Mostra o valor do desvio-padrão
print(k.std())

8.615231988880057


In [54]:
# Funções universais, aplicadas a todos os elementos
# Mostra o valor da raíz quadrada de todos os elemntos
k1 = np.array([1, 4, 9, 16, 25, 36])
print(np.sqrt(k1))

[1. 2. 3. 4. 5. 6.]


In [56]:
# Mostra o valor do exponencial de todos os elementos
print(np.exp(k1))

[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06
 7.20048993e+10 4.31123155e+15]


In [57]:
# Extração de todos os elementos
m = np.array([1,2,3,4,5,6])
# Mostra o elemento na posição 2
print(m[1])

2


In [61]:
# Mostra o array criado a partir da posição 0, dois elementos
print(m[0:2])

[1 2]


In [62]:
# Mostra o array criado a partir da 2ª posição
# Até todo o restante do array
print(m[1:])

[2 3 4 5 6]


In [63]:
# Mostra o array criado a partir da antepenúltima
# posição até o final
print(m[-3:])

[4 5 6]


In [65]:
# Extração das linhas e colunas
l = np.array([[4,5], [6,1], [7,4]])
print(l)

[[4 5]
 [6 1]
 [7 4]]


In [67]:
# Primeira linha todas as colunas
l_linha_1 = l[0,:]
print(l_linha_1)

[4 5]


In [69]:
# Segunda linha
l_linha_2 = l[1,:]
print(l_linha_2)

[6 1]


In [70]:
# Terceira linha
l_linha_3 = l[2,:]
print(l_linha_3)

[7 4]


In [72]:
# Todas as linhas, primeira coluna
l_coluna_1 = l[:,0]
print(l_coluna_1)

[4 6 7]


In [73]:
# Todas as linhas, segunda coluna
l_coluna_2 = l[:,1]
print(l_coluna_2)

[5 1 4]


In [3]:
# Adição e multiplicação de matrizes
n = np.array([[1,2],[3,4]])
o = np.array([[1,1],[1,1]])
res1 = n + o

In [4]:
print(res1)

[[2 3]
 [4 5]]


In [5]:
p = np.array([[1,2],[3,4],[5,6]])
q = np.array([[2,1]])
print(p+q)

[[3 3]
 [5 5]
 [7 7]]


In [6]:
# Transposição, rearranja um conjunto de 15 elementos de 0 a 14
# em 3 linhas e 5 colunas
f = np.arange(15).reshape((3,5))
# Mostra as matrizes transpostas entre linhas e colunas
print(f)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [8]:
s = f.T
print(s)

[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [10]:
# Outra forma de fazer, mesmo resultado
r = np.arange(15).reshape((3,5))
print(r)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [12]:
# Rearranja um conjunto de 15 elementos
# Mostra as matrizes transpostas entre linha e coluna
s = r.transpose((1,0))
print(s)

[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [13]:
# Expressões lógicas
# usando where
# criando matriz com valores booleanos baseado no array v
v = np.random.randn(4,4)
print(v)

[[ 0.10311981  0.61403448  0.28371503  1.26924721]
 [-1.62045614  0.85100831  1.39622967 -0.56829496]
 [-0.40148889  0.49418569 -0.95619527  0.84231877]
 [ 0.60321185 -0.79899956 -0.31503524 -0.33935278]]


In [14]:
# criando matriz com valores booleanos baseados no array v
x = (v > 0)
print(x)

[[ True  True  True  True]
 [False  True  True False]
 [False  True False  True]
 [ True False False False]]


In [15]:
# Criando matriz com valores -1 e 1 baseados nos valores do array x
z = np.where(x > 0, 1, -1)
print(z)

[[ 1  1  1  1]
 [-1  1  1 -1]
 [-1  1 -1  1]
 [ 1 -1 -1 -1]]


## 7. Pandas

- Dois tipos de dados:
  * Data Frame
  * Series
- Ex.:
  * Importando o Pandas e os dados:
    - import pandas as pd
    - dados = pd.read_csv('basecensus.csv')

In [1]:
# Importar o Pandas
import pandas as pd

In [2]:
# Carregar arquivo para dataframe Pandas
dados = pd.read_csv("Dados/Credit.csv")
# Formato
dados.shape

(1000, 21)

In [3]:
# Resumo estatístico de coluna numéricos
dados.describe()

duration  credit_amount  installment_commitment  residence_since  \
count  1000.000000    1000.000000             1000.000000      1000.000000   
mean     20.903000    3271.258000                2.973000         2.845000   
std      12.058814    2822.736876                1.118715         1.103718   
min       4.000000     250.000000                1.000000         1.000000   
25%      12.000000    1365.500000                2.000000         2.000000   
50%      18.000000    2319.500000                3.000000         3.000000   
75%      24.000000    3972.250000                4.000000         4.000000   
max      72.000000   18424.000000                4.000000         4.000000   

               age  existing_credits  num_dependents  
count  1000.000000       1000.000000     1000.000000  
mean     35.546000          1.407000        1.155000  
std      11.375469          0.577654        0.362086  
min      19.000000          1.000000        1.000000  
25%      27.000000          1.000000        1.000000  
50%      33.000000          1.000000        1.000000  
75%      42.000000          2.000000        1.000000  
max      75.000000          4.000000        2.000000

In [4]:
# Primeiros registros
dados.head()

checking_status  duration                    credit_history  \
0              <0         6  'critical/other existing credit'   
1        0<=X<200        48                   'existing paid'   
2   'no checking'        12  'critical/other existing credit'   
3              <0        42                   'existing paid'   
4              <0        24              'delayed previously'   

               purpose  credit_amount      savings_status employment  \
0             radio/tv           1169  'no known savings'        >=7   
1             radio/tv           5951                <100     1<=X<4   
2            education           2096                <100     4<=X<7   
3  furniture/equipment           7882                <100     4<=X<7   
4            'new car'           4870                <100     1<=X<4   

   installment_commitment       personal_status other_parties  ...  \
0                       4         'male single'          none  ...   
1                       2  'female div/dep/mar'          none  ...   
2                       2         'male single'          none  ...   
3                       2         'male single'     guarantor  ...   
4                       3         'male single'          none  ...   

    property_magnitude age  other_payment_plans     housing existing_credits  \
0        'real estate'  67                 none         own                2   
1        'real estate'  22                 none         own                1   
2        'real estate'  49                 none         own                1   
3     'life insurance'  45                 none  'for free'                1   
4  'no known property'  53                 none  'for free'                2   

                    job num_dependents  own_telephone foreign_worker class  
0               skilled              1            yes            yes  good  
1               skilled              1           none            yes   bad  
2  'unskilled resident'              2           none            yes  good  
3               skilled              2           none            yes  good  
4               skilled              2           none            yes   bad  

[5 rows x 21 columns]

In [5]:
# Últimos registros, com parâmetros
dados.tail()

checking_status  duration                    credit_history  \
995   'no checking'        12                   'existing paid'   
996              <0        30                   'existing paid'   
997   'no checking'        12                   'existing paid'   
998              <0        45                   'existing paid'   
999        0<=X<200        45  'critical/other existing credit'   

                 purpose  credit_amount savings_status  employment  \
995  furniture/equipment           1736           <100      4<=X<7   
996           'used car'           3857           <100      1<=X<4   
997             radio/tv            804           <100         >=7   
998             radio/tv           1845           <100      1<=X<4   
999           'used car'           4576     100<=X<500  unemployed   

     installment_commitment       personal_status other_parties  ...  \
995                       3  'female div/dep/mar'          none  ...   
996                       4        'male div/sep'          none  ...   
997                       4         'male single'          none  ...   
998                       4         'male single'          none  ...   
999                       3         'male single'          none  ...   

      property_magnitude age  other_payment_plans     housing  \
995        'real estate'  31                 none         own   
996     'life insurance'  40                 none         own   
997                  car  38                 none         own   
998  'no known property'  23                 none  'for free'   
999                  car  27                 none         own   

    existing_credits                          job num_dependents  \
995                1         'unskilled resident'              1   
996                1  'high qualif/self emp/mgmt'              1   
997                1                      skilled              1   
998                1                      skilled              1   
999                1                      skilled              1   

     own_telephone foreign_worker class  
995           none            yes  good  
996            yes            yes  good  
997           none            yes  good  
998            yes            yes   bad  
999           none            yes  good  

[5 rows x 21 columns]

In [7]:
# Filtros por nome da coluna
dados[['duration']]

duration
0           6
1          48
2          12
3          42
4          24
..        ...
995        12
996        30
997        12
998        45
999        45

[1000 rows x 1 columns]

In [8]:
# Filtrar linhas por índice
dados.loc[1:3]

checking_status  duration                    credit_history  \
1        0<=X<200        48                   'existing paid'   
2   'no checking'        12  'critical/other existing credit'   
3              <0        42                   'existing paid'   

               purpose  credit_amount savings_status employment  \
1             radio/tv           5951           <100     1<=X<4   
2            education           2096           <100     4<=X<7   
3  furniture/equipment           7882           <100     4<=X<7   

   installment_commitment       personal_status other_parties  ...  \
1                       2  'female div/dep/mar'          none  ...   
2                       2         'male single'          none  ...   
3                       2         'male single'     guarantor  ...   

   property_magnitude age  other_payment_plans     housing existing_credits  \
1       'real estate'  22                 none         own                1   
2       'real estate'  49                 none         own                1   
3    'life insurance'  45                 none  'for free'                1   

                    job num_dependents  own_telephone foreign_worker class  
1               skilled              1           none            yes   bad  
2  'unskilled resident'              2           none            yes  good  
3               skilled              2           none            yes  good  

[3 rows x 21 columns]

In [9]:
# Linhas 1 e 3
dados.loc[[1,3]]

checking_status  duration   credit_history              purpose  \
1        0<=X<200        48  'existing paid'             radio/tv   
3              <0        42  'existing paid'  furniture/equipment   

   credit_amount savings_status employment  installment_commitment  \
1           5951           <100     1<=X<4                       2   
3           7882           <100     4<=X<7                       2   

        personal_status other_parties  ...  property_magnitude age  \
1  'female div/dep/mar'          none  ...       'real estate'  22   
3         'male single'     guarantor  ...    'life insurance'  45   

   other_payment_plans     housing existing_credits      job num_dependents  \
1                 none         own                1  skilled              1   
3                 none  'for free'                1  skilled              2   

   own_telephone foreign_worker class  
1           none            yes   bad  
3           none            yes  good  

[2 rows x 21 columns]

In [10]:
# Filtro
dados.loc[dados['purpose']=='radio e tv']

Empty DataFrame
Columns: [checking_status, duration, credit_history, purpose, credit_amount, savings_status, employment, installment_commitment, personal_status, other_parties, residence_since, property_magnitude, age, other_payment_plans, housing, existing_credits, job, num_dependents, own_telephone, foreign_worker, class]
Index: []

[0 rows x 21 columns]

In [14]:
# Outra condição
dados.loc[dados['credit_amount'] > 18000]

checking_status  duration         credit_history purpose  credit_amount  \
915        0<=X<200        48  'no credits/all paid'   other          18424   

    savings_status employment  installment_commitment       personal_status  \
915           <100     1<=X<4                       1  'female div/dep/mar'   

    other_parties  ...  property_magnitude age  other_payment_plans housing  \
915          none  ...    'life insurance'  32                 bank     own   

    existing_credits                          job num_dependents  \
915                1  'high qualif/self emp/mgmt'              1   

     own_telephone foreign_worker class  
915            yes             no   bad  

[1 rows x 21 columns]

In [17]:
# Atribuimos resultado a variável, criando outro df
credito2 = dados.loc[dados['credit_amount']>18000]
credito2

checking_status  duration         credit_history purpose  credit_amount  \
915        0<=X<200        48  'no credits/all paid'   other          18424   

    savings_status employment  installment_commitment       personal_status  \
915           <100     1<=X<4                       1  'female div/dep/mar'   

    other_parties  ...  property_magnitude age  other_payment_plans housing  \
915          none  ...    'life insurance'  32                 bank     own   

    existing_credits                          job num_dependents  \
915                1  'high qualif/self emp/mgmt'              1   

     own_telephone foreign_worker class  
915            yes             no   bad  

[1 rows x 21 columns]

In [19]:
# Definimos só algumas colunas
credito3 = dados[['checking_status','duration']].loc[dados['credit_amount'] > 18000]
credito3

checking_status  duration
915        0<=X<200        48

In [20]:
# Séries, única oluna
# Pode ser criada a partir de listas, array do numpy ou coluna do dataframe
s1 = pd.Series([2,5,3,34,54,23,1,16])
s1

0     2
1     5
2     3
3    34
4    54
5    23
6     1
7    16
dtype: int64

In [23]:
# Série a partir de um array do Numpy
import numpy as np
array1 = np.array([2,5,3,34,54,23,1,16])
s2 = pd.Series(array1)
s2

0     2
1     5
2     3
3    34
4    54
5    23
6     1
7    16
dtype: int32

In [24]:
# Séries a partir de um dataframe
s3 = dados['purpose']
s3

0                 radio/tv
1                 radio/tv
2                education
3      furniture/equipment
4                'new car'
              ...         
995    furniture/equipment
996             'used car'
997               radio/tv
998               radio/tv
999             'used car'
Name: purpose, Length: 1000, dtype: object

In [27]:
# Renomear
dados.rename(columns={"duration":"duração", "purpose":"propósito"})

checking_status  duração                    credit_history  \
0                <0        6  'critical/other existing credit'   
1          0<=X<200       48                   'existing paid'   
2     'no checking'       12  'critical/other existing credit'   
3                <0       42                   'existing paid'   
4                <0       24              'delayed previously'   
..              ...      ...                               ...   
995   'no checking'       12                   'existing paid'   
996              <0       30                   'existing paid'   
997   'no checking'       12                   'existing paid'   
998              <0       45                   'existing paid'   
999        0<=X<200       45  'critical/other existing credit'   

               propósito  credit_amount      savings_status  employment  \
0               radio/tv           1169  'no known savings'         >=7   
1               radio/tv           5951                <100      1<=X<4   
2              education           2096                <100      4<=X<7   
3    furniture/equipment           7882                <100      4<=X<7   
4              'new car'           4870                <100      1<=X<4   
..                   ...            ...                 ...         ...   
995  furniture/equipment           1736                <100      4<=X<7   
996           'used car'           3857                <100      1<=X<4   
997             radio/tv            804                <100         >=7   
998             radio/tv           1845                <100      1<=X<4   
999           'used car'           4576          100<=X<500  unemployed   

     installment_commitment       personal_status other_parties  ...  \
0                         4         'male single'          none  ...   
1                         2  'female div/dep/mar'          none  ...   
2                         2         'male single'          none  ...   
3                         2         'male single'     guarantor  ...   
4                         3         'male single'          none  ...   
..                      ...                   ...           ...  ...   
995                       3  'female div/dep/mar'          none  ...   
996                       4        'male div/sep'          none  ...   
997                       4         'male single'          none  ...   
998                       4         'male single'          none  ...   
999                       3         'male single'          none  ...   

      property_magnitude age  other_payment_plans     housing  \
0          'real estate'  67                 none         own   
1          'real estate'  22                 none         own   
2          'real estate'  49                 none         own   
3       'life insurance'  45                 none  'for free'   
4    'no known property'  53                 none  'for free'   
..                   ...  ..                  ...         ...   
995        'real estate'  31                 none         own   
996     'life insurance'  40                 none         own   
997                  car  38                 none         own   
998  'no known property'  23                 none  'for free'   
999                  car  27                 none         own   

    existing_credits                          job num_dependents  \
0                  2                      skilled              1   
1                  1                      skilled              1   
2                  1         'unskilled resident'              2   
3                  1                      skilled              2   
4                  2                      skilled              2   
..               ...                          ...            ...   
995                1         'unskilled resident'              1   
996                1  'high qualif/self emp/mgmt'              1   
997                1                      skilled   

In [28]:
# Porém a alteração não é persistida
dados.head(1)

checking_status  duration                    credit_history   purpose  \
0              <0         6  'critical/other existing credit'  radio/tv   

   credit_amount      savings_status employment  installment_commitment  \
0           1169  'no known savings'        >=7                       4   

  personal_status other_parties  ...  property_magnitude age  \
0   'male single'          none  ...       'real estate'  67   

   other_payment_plans housing existing_credits      job num_dependents  \
0                 none     own                2  skilled              1   

   own_telephone foreign_worker class  
0            yes            yes  good  

[1 rows x 21 columns]

In [31]:
# Para persistir a alteração
dados.rename(columns={"duration":"duração","purpose":"próposito"}, inplace=True)

In [32]:
dados.head(1)

checking_status  duração                    credit_history próposito  \
0              <0        6  'critical/other existing credit'  radio/tv   

   credit_amount      savings_status employment  installment_commitment  \
0           1169  'no known savings'        >=7                       4   

  personal_status other_parties  ...  property_magnitude age  \
0   'male single'          none  ...       'real estate'  67   

   other_payment_plans housing existing_credits      job num_dependents  \
0                 none     own                2  skilled              1   

   own_telephone foreign_worker class  
0            yes            yes  good  

[1 rows x 21 columns]

In [33]:
# Excluir coluna
dados.drop('checking_status',axis=1,inplace=True)

In [34]:
dados.head(1)

duração                    credit_history próposito  credit_amount  \
0        6  'critical/other existing credit'  radio/tv           1169   

       savings_status employment  installment_commitment personal_status  \
0  'no known savings'        >=7                       4   'male single'   

  other_parties  residence_since property_magnitude  age other_payment_plans  \
0          none                4      'real estate'   67                none   

  housing  existing_credits      job  num_dependents own_telephone  \
0     own                 2  skilled               1           yes   

  foreign_worker class  
0            yes  good

In [35]:
# Verificar dados nulos
dados.isnull()

duração  credit_history  próposito  credit_amount  savings_status  \
0      False           False      False          False           False   
1      False           False      False          False           False   
2      False           False      False          False           False   
3      False           False      False          False           False   
4      False           False      False          False           False   
..       ...             ...        ...            ...             ...   
995    False           False      False          False           False   
996    False           False      False          False           False   
997    False           False      False          False           False   
998    False           False      False          False           False   
999    False           False      False          False           False   

     employment  installment_commitment  personal_status  other_parties  \
0         False                   False            False          False   
1         False                   False            False          False   
2         False                   False            False          False   
3         False                   False            False          False   
4         False                   False            False          False   
..          ...                     ...              ...            ...   
995       False                   False            False          False   
996       False                   False            False          False   
997       False                   False            False          False   
998       False                   False            False          False   
999       False                   False            False          False   

     residence_since  property_magnitude    age  other_payment_plans  housing  \
0              False               False  False                False    False   
1              False               False  False                False    False   
2              False               False  False                False    False   
3              False               False  False                False    False   
4              False               False  False                False    False   
..               ...                 ...    ...                  ...      ...   
995            False               False  False                False    False   
996            False               False  False                False    False   
997            False               False  False                False    False   
998            False               False  False                False    False   
999            False               False  False                False    False   

     existing_credits    job  num_dependents  own_telephone  foreign_worker  \
0               False  False           False          False           False   
1               False  False           False          False           False   
2               False  False           False          False           False   
3               False  False           False          False           False   
4               False  False           False          False           False   
..                ...    ...             ...            ...             ...   
995             False  False           False          False           False   
996             False  False           False          False           False   
997             False  False           False          False           False   
998             False  False           False          False           False   
999             False  False           False          False           False   

     class  
0    False  
1    False  
2    False  
3    False  
4    False  
..     ...  
995  False  
996  False  
997  False  
998  False  
999  False  

[1000 rows x 20 columns]

In [37]:
# Verificar dados nulos
dados.isnull().sum()

duração                   0
credit_history            0
próposito                 0
credit_amount             0
savings_status            0
employment                0
installment_commitment    0
personal_status           0
other_parties             0
residence_since           0
property_magnitude        0
age                       0
other_payment_plans       0
housing                   0
existing_credits          0
job                       0
num_dependents            0
own_telephone             0
foreign_worker            0
class                     0
dtype: int64

In [38]:
# Retirar colunas com NaN
dados.dropna()

duração                    credit_history            próposito  \
0          6  'critical/other existing credit'             radio/tv   
1         48                   'existing paid'             radio/tv   
2         12  'critical/other existing credit'            education   
3         42                   'existing paid'  furniture/equipment   
4         24              'delayed previously'            'new car'   
..       ...                               ...                  ...   
995       12                   'existing paid'  furniture/equipment   
996       30                   'existing paid'           'used car'   
997       12                   'existing paid'             radio/tv   
998       45                   'existing paid'             radio/tv   
999       45  'critical/other existing credit'           'used car'   

     credit_amount      savings_status  employment  installment_commitment  \
0             1169  'no known savings'         >=7                       4   
1             5951                <100      1<=X<4                       2   
2             2096                <100      4<=X<7                       2   
3             7882                <100      4<=X<7                       2   
4             4870                <100      1<=X<4                       3   
..             ...                 ...         ...                     ...   
995           1736                <100      4<=X<7                       3   
996           3857                <100      1<=X<4                       4   
997            804                <100         >=7                       4   
998           1845                <100      1<=X<4                       4   
999           4576          100<=X<500  unemployed                       3   

          personal_status other_parties  residence_since   property_magnitude  \
0           'male single'          none                4        'real estate'   
1    'female div/dep/mar'          none                2        'real estate'   
2           'male single'          none                3        'real estate'   
3           'male single'     guarantor                4     'life insurance'   
4           'male single'          none                4  'no known property'   
..                    ...           ...              ...                  ...   
995  'female div/dep/mar'          none                4        'real estate'   
996        'male div/sep'          none                4     'life insurance'   
997         'male single'          none                4                  car   
998         'male single'          none                4  'no known property'   
999         'male single'          none                4                  car   

     age other_payment_plans     housing  existing_credits  \
0     67                none         own                 2   
1     22                none         own                 1   
2     49                none         own                 1   
3     45                none  'for free'                 1   
4     53                none  'for free'                 2   
..   ...                 ...         ...               ...   
995   31                none         own                 1   
996   40                none         own                 1   
997   38                none         own                 1   
998   23                none  'for free'                 1   
999   27                none         own                 1   

                             job  num_dependents own_telephone foreign_worker  \
0                        skilled               1           yes            yes   
1                        skilled               1          none            yes   
2           'unskilled resident'               2          none            yes   
3                        skilled               2          none            yes   
4                        skilled               2          none            yes   
..         

In [39]:
# Preencher dados faltantes
dados['duração'].fillna(0,inplace=True)

In [40]:
# Iloc
dados.iloc[0:3,0:5]

duração                    credit_history  próposito  credit_amount  \
0        6  'critical/other existing credit'   radio/tv           1169   
1       48                   'existing paid'   radio/tv           5951   
2       12  'critical/other existing credit'  education           2096   

       savings_status  
0  'no known savings'  
1                <100  
2                <100

In [ ]:
dados.iloc[[0,1,2,3,7],0:5]

## 8. Módulos e pacotes

#### Módulos:
- Conjuntos de funcionalidades organizadas em arquivos.
- Usando funções de um módulo:
  * import statistics
  * x = statistics.mean(z)
  * y = statistics.median(z)
- Usando nome alternativo:
  * import statistics as est
  * x = est.mean(z)
  * y = est.median(z)
- Usando sem nome do módulo:
  * from statistics import mean, median
    * mean()
    * median()
  * from statistics import *

#### Pacotes:
- Permite organizar módulos usando um notação de pontos.
- Ex.: import cienciadados.estatistica, cienciadedados.machinelearning
- Instalando um pacote:
  * python -m ensurepip -- default-pip (Prompt de Comando)
  * !pip install numpy

In [45]:
import statistics as est

In [46]:
z = [10,20,30,40]

In [48]:
x = est.mean(z)
x

25

In [49]:
y = est.median(z)
y

25.0

In [50]:
from statistics import mean, median

In [51]:
z = [10,20,30,40]

In [52]:
x = mean(z)
x

25

In [53]:
y = median(z)
y

25.0

In [54]:
from statistics import *

In [55]:
z = [10,20,30,40]

In [56]:
x = mean(z)
x

25

In [57]:
y = median(z)
y

25.0

## 9. Funções

- Blocos de Código Reutilizáveis
- Podem ser chamados de qualquer parte do programa
- Podem ser chamados de outros programas

In [60]:
def imprime():
    print("esta é uma função")

imprime()

esta é uma função


In [62]:
# Com parâmetro
def imprime(n):
    print(n)

imprime("Impressão deste texto")

Impressão deste texto


In [63]:
# Com retorno
def potencia(n):
    return n * n

x = potencia(3)
print(x)

9


In [69]:
# Com valor default
def intervalo(inic=1, fim=10):
    for inic in range(1, fim+1):
        print(inic)

x = intervalo(1,10)

1
2
3
4
5
6
7
8
9
10


In [70]:
y = intervalo()

1
2
3
4
5
6
7
8
9
10


## 10. Funções padrão

- Internas:
  * Sem o uso de import
  * abs()
  * max()
  * min()
  * round()
  * sum()
  
- Modulos “Nativos”:
  - from statistics import *
  - mean()
  - median()
  - mode()
  - stdev()
  - variance()
  
- Instalação:
  * python -m pip install numpy
  * from numpy import *
  * a = random.random((8,8))

In [71]:
# Funções internas
print(abs(-200))

200


In [72]:
lst = [1,2,30,30,45]

In [73]:
print("Maior valor: ", max(lst))

Maior valor:  45


In [74]:
print("Menor valor: ", min(lst))

Menor valor:  1


In [75]:
print("Soma: ", sum(lst))

Soma:  108


In [76]:
print("Arrendondamento: ", round(2.34567,2))

Arrendondamento:  2.35


In [77]:
# Statistics
from statistics import *

In [78]:
print("Média: ", mean(lst))

Média:  21.6


In [79]:
print("Mediana: ", median(lst))

Mediana:  30


In [81]:
print("Moda: ", mode(lst))

Moda:  30


In [83]:
# Desvio padrão da amostra
print("Desvio padrão: ", stdev(lst))

Desvio padrão:  19.346834366376324


In [84]:
# Variância da amostra
print("Variância: ", variance(lst))

Variância:  374.3


In [86]:
from numpy import *

In [88]:
a = random.random((8,8))

In [89]:
print(type(a))

<class 'numpy.ndarray'>


In [90]:
print(a)

[[0.30628934 0.38232637 0.18946353 0.87572275 0.23856687 0.5543135
  0.93024696 0.88049592]
 [0.77017664 0.08823744 0.4162682  0.61175492 0.09687955 0.95678397
  0.60887716 0.07168943]
 [0.06651596 0.72570404 0.97513163 0.38142952 0.88136501 0.23714138
  0.5523809  0.72587892]
 [0.69320932 0.50643451 0.37180248 0.11799642 0.64570446 0.45364749
  0.07876834 0.70000824]
 [0.08245706 0.43411316 0.85545775 0.90773769 0.37010204 0.56178925
  0.63098057 0.97206621]
 [0.88455142 0.79246783 0.85445174 0.4867824  0.36369497 0.25335773
  0.03472222 0.61488278]
 [0.57791402 0.51113941 0.34135445 0.20153811 0.18152581 0.65253635
  0.62311496 0.84346817]
 [0.35209594 0.2970951  0.73595669 0.5933736  0.84278292 0.92293189
  0.96320963 0.03309198]]
